"""Add some more user fields

Revision ID: 65fbcbbbec94
Revises: 6614910ad05f
Create Date: 2024-09-19 20:46:35.392102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fbcbbbec94'
down_revision = '6614910ad05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('participant_service', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('participant_service')
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
