"""Add quiz_completed to User

Revision ID: 9ac8c3d69bae
Revises: 7ca071d41c84
Create Date: 2024-10-07 16:15:23.575592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac8c3d69bae'
down_revision = '7ca071d41c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_completed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('quiz_completed')

    # ### end Alembic commands ###
