"""Update user to add participant status

Revision ID: a69caa636752
Revises: 65fbcbbbec94
Create Date: 2024-09-26 16:32:26.963433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69caa636752'
down_revision = '65fbcbbbec94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_status', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('participant_status')

    # ### end Alembic commands ###
